
spring:
  zipkin:
    base-url: http://localhost:9411/
  application:
    name: product-service
  datasource:
    url: jdbc:mysql://localhost:3306/product-serice-1
    username: root
    password: Huynguyen11102002
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update

server:
  port: 9090
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/



