spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
  cloud:
    bus:
      enabled: true
      refresh:
        enabled: true  zipkin:    base-url: http://localhost:9411/
logging:  file:    name: C:/Users/Admin/Desktop/elkstack/elklogs.log